export let perguntas = [
  {
    pergunta: "Quantos dentes tem um humano saudável?",
    resposta1: "5",
    resposta2: "32",
    resposta3: "50",
    resposta4: "100",
    solucao: "B",
  },
  {
    pergunta: "Quantos ossos tem um humano saudável?",
    resposta1: "10563",
    resposta2: "5",
    resposta3: "0",
    resposta4: "206",
    solucao: "D",
  },
  {
    pergunta: "Qual é o maior orgão do corpo humano?",
    resposta1: "Pele",
    resposta2: "Pé",
    resposta3: "Olho",
    resposta4: "Cabelo",
    solucao: "A",
  },
  {
    //2
    pergunta: "Qual é o maior sistema do corpo humano?",
    resposta1: "Sistema Tegumentar (Pele)",
    resposta2: "Sistema Digestivo",
    resposta3: "Sistema Reprodutor",
    resposta4: "Sistema Esquelético",
    solucao: "A",
  },
  {
    pergunta: "Qual o orgão mais pesado do corpo humano?",
    resposta1: "Pulmão",
    resposta2: "Pele",
    resposta3: "Coração",
    resposta4: "Cerebro",
    solucao: "B",
  },
  {
    pergunta: "Quantos litros de sangue uma pessoa saudavel tem no corpo?",
    resposta1: "60L",
    resposta2: "100L",
    resposta3: "Média 5L",
    resposta4: "0L",
    solucao: "C",
  },
  {
    pergunta: "Qual a mior ortéria do corpo?",
    resposta1: "Veia Esquerda",
    resposta2: "Veia Direita",
    resposta3: "Arteria Esquerda",
    resposta4: "Aorta",
    solucao: "D",
  },
  {
    pergunta: "Qual desdes é um prato tipico português?",
    resposta1: "Sushi",
    resposta2: "Lasanha",
    resposta3: "Francesinha",
    resposta4: "Pizza",
    solucao: "C",
  },
  {
    pergunta: "Capital de portugal?",
    resposta1: "Lisboa",
    resposta2: "Porto",
    resposta3: "Coimbra",
    resposta4: "Algarve",
    solucao: "A",
  },
  {
    pergunta: "Ano do Grande terramoto em Lisboa?",
    resposta1: "2000",
    resposta2: "1755",
    resposta3: "1000",
    resposta4: "1500",
    solucao: "B",
  },
  {
    pergunta: "Como eram chamados os árabes pelos portugues?",
    resposta1: "Arrabes",
    resposta2: "Loucos",
    resposta3: "Mouros",
    resposta4: "Barbudos",
    solucao: "C",
  },
  {
    pergunta: "Segunda lingua oficial de Portugal?",
    resposta1: "Japonês",
    resposta2: "Irlandês",
    resposta3: "Russo",
    resposta4: "Mirandês",
    solucao: "D",
  },
  {
    pergunta: "Música tradicional portuguesa?",
    resposta1: "Fado",
    resposta2: "Rock",
    resposta3: "Samba",
    resposta4: "Tango",
    solucao: "A",
  },
  {
    pergunta: "Primeiro rei de portugal?",
    resposta1: "D. João Segundo",
    resposta2: "D. Afonso Henrriques",
    resposta3: "Zé Castelo Branco",
    resposta4: "Maria Leal",
    solucao: "B",
  },
  {
    pergunta:
      "Qual destes é uma 'antropomorfização' portuguesa (personificação naciona)?",
    resposta1: "Zé Castelo Branco",
    resposta2: "D. Afonso Henrriques",
    resposta3: "Zé Povinho",
    resposta4: "Maria Leal",
    solucao: "C",
  },
  {
    pergunta:
      "Qual destes é uma 'antropomorfização' portuguesa (personificação naciona)?",
    resposta1: "Maria Leal",
    resposta2: "D. Afonso Henrriques",
    resposta3: "Vasco da Gama",
    resposta4: "Efígie da República",
    solucao: "D",
  },
  {
    pergunta:
      "Qual destes é uma 'antropomorfização' portuguesa (personificação naciona)?",
    resposta1: "Galo de Barcelos",
    resposta2: "D. Afonso Henrriques",
    resposta3: "Cristina Ferreira",
    resposta4: "Maria Leal",
    solucao: "A",
  },
];
