const resp = document.getElementById("resp");

const btnIgual = document.getElementById("btn-Igual");
const btnNove = document.getElementById("btn-Nove");
const btnOito = document.getElementById("btn-Oito");
const btnSete = document.getElementById("btn-Sete");
const btnSeis = document.getElementById("btn-Seis");
const btnCinco = document.getElementById("btn-Cinco");
const btnQuatro = document.getElementById("btn-Quatro");
const btnTres = document.getElementById("btn-Tres");
const btnDois = document.getElementById("btn-Dois");
const btnUm = document.getElementById("btn-Um");
const btnZero = document.getElementById("btn-Zero");
const btnPi = document.getElementById("btn-Pi");
const btnDiv = document.getElementById("btn-Div");
const btnMult = document.getElementById("btn-Mult");
const btnSoma = document.getElementById("btn-Soma");
const btnSub = document.getElementById("btn-Sub");
const btnQuadrado = document.getElementById("btn-Quadrado");
const btnCubo = document.getElementById("btn-Cubo");
const btnPotencia = document.getElementById("btn-Potencia");

const mensagem = "Algo deu muito errado";

btnIgual.addEventListener("click", () => resp.innerHTML = mensagem);
btnNove.addEventListener("click", () => resp.innerHTML = mensagem);
btnOito.addEventListener("click", () => resp.innerHTML = mensagem);
btnSete.addEventListener("click", () => resp.innerHTML = mensagem);
btnSeis.addEventListener("click", () => resp.innerHTML = mensagem);
btnCinco.addEventListener("click", () => resp.innerHTML = mensagem);
btnQuatro.addEventListener("click", () => resp.innerHTMLmensagem = mensagem);
btnTres.addEventListener("click", () => resp.innerHTML = mensagem);
btnDois.addEventListener("click", () => resp.innerHTML = mensagem);
btnUm.addEventListener("click", () => resp.innerHTML = mensagem);
btnZero.addEventListener("click", () => resp.innerHTML = mensagem);
btnPi.addEventListener("click", () => resp.innerHTML = mensagem);
btnDiv.addEventListener("click", () => resp.innerHTML = mensagem);
btnMult.addEventListener("click", () => resp.innerHTML = mensagem);
btnSoma.addEventListener("click", () => resp.innerHTML = mensagem);
btnSub.addEventListener("click", () => resp.innerHTML = mensagem);
btnQuadrado.addEventListener("click", () => resp.innerHTmensagem = mensagem);
btnCubo.addEventListener("click", () => resp.innerHTML = mensagem);
btnPotencia.addEventListener("click", () => resp.innerHTML = mensagem);