export const links = [ // Paginas
  "./Pages/AmazingSites/",
  "./Pages/AnimacaoBola/",
  "./Pages/AnimacaoDiv/",
  // "./Pages/AvatarBuilder/",
  // "./Pages/BatataMan/",
  "./Pages/Bloop/",
  "./Pages/BoxStyle/",
  "./Pages/Calculadora/",
  "./Pages/ChuvaBolas/",
  "./Pages/Covide19/",
  "./Pages/DadosUser/",
  "./Pages/DancaQuadrado/",
  "./Pages/DescobrirPP/",
  "./Pages/EventosRato/",
  "./Pages/FormNetlify/",
  "./Pages/Iluminacao/",
  "./Pages/Infinity3D/",
  "./Pages/Linguagem/",
  "./Pages/Loading/",
  "./Pages/Luz/",
  "./Pages/MeiaGaspea/",
  "./Pages/Neon/",
  "./Pages/Ninica/",
  "./Pages/PalavraMagica/",
  // "./Pages/Publicidade/",
  "./Pages/SegueRato/",
  "./Pages/SegundoContador/",
  "./Pages/Semaforo/",
  "./Pages/Skills/",
  "./Pages/Sozinho/",
  "./Pages/StarWars/",
  "./Pages/SVGCoracao/",
  "./Pages/TagFixes/",
  "./Pages/Tarefas/",
  "./Pages/Tempo/",
  "./Pages/TempoSobra/",
  // "./Pages/Visitas/",
  "./Pages/Xadrez/",
];
